serve:
  - serve_id: vllm_model
    engine: vllm
    engine_args:
      model: /root/.cache/modelscope/hub/models/Qwen/Qwen3-4B
      host: 0.0.0.0
      served-model-name: Qwen/Qwen3-4B
      uvicorn_log_level: warning
      port: 2026
      trust_remote_code: true
      gpu_memory_utilization: 0.9
      pipeline_parallel_size: 1
      tensor_parallel_size: 1
      block_size: 128
      max_num_seqs: 1
      max_model_len: 20480
      max_num_batched_tokens: 40960
      dtype: bfloat16
      enforce_eager: true
      enable_prefix_caching: true
      enable_chunked_prefill: true
      disable_log_stats: true
      async_scheduling: true

experiment:
  exp_name: qwen3_4b
  exp_dir: s2_0/${experiment.exp_name}
  task:
    type: serve
  runner:
    hostfile: null
    deploy:
      use_fs_serve: false
  envs:
    ASCEND_RT_VISIBLE_DEVICES: 0
    ASCEND_RT_DEVICE_MAX_CONNECTIONS: 8

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
